// Main -> Global hints
MENU(Hints) = [
    ["Global Hints", true],
    ["FF Warning",              [0], "", -5, [["expression", "['FFWarn'] remoteExec ['AW_fnc_zeusToolsHint', 2]"]], "1", "1"],
    ["Zeus spam",               [0], "", -5, [["expression", "['ZeusSpam'] remoteExec ['AW_fnc_zeusToolsHint', 2]"]], "1", "1"],
    ["Zeus active",             [0], "", -5, [["expression", "['ZeusActive'] remoteExec ['AW_fnc_zeusToolsHint', 2]"]], "1", "1"],
    ["Steal vehicle warning",   [0], "", -5, [["expression", "['StealVehicle'] remoteExec ['AW_fnc_zeusToolsHint', 2]"]], "1", "1"],
    ["Uncalled CAS warning",    [0], "", -5, [["expression", "['CASWarn'] remoteExec ['AW_fnc_zeusToolsHint', 2]"]], "1", "1"],
    ["Clear Hints",             [0], "", -5, [["expression", "remoteExec ['AW_fnc_zeusToolsHint', 2]"]], "1", "1"]
];
